name: "Bump Version (Magus.Json)"
on:
  push:
    branches:
      - main
    paths:
      - "src/Magus.Unity/Assets/Scripts/Magus.Json/**"
jobs:
  bump-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: "v"
          tag-suffix: "-json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: "src/Magus.Unity/Assets/Scripts/Magus.Json"
      - name: "cat package.json"
        run: cat ./src/Magus.Unity/Assets/Scripts/Magus.Json/package.json
      - name: "Output Step"
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"